### ISSUE TITLE
Filter hospital information and contact relevant ones

### ISSUE THREAD

**Issue by ChristinaLast** [ChristinaLast/pollution_analysis_kurdistan#32]
### Tasks associated 
- [x] define criteria for filtering (e.g. presence of email, url, etc.), may depend on completion of #11 for pollution metrics
  - [ ] Translate columns in arabic to english (in python if possible)
- [x] create function to filter [hospital csv](https://drive.google.com/file/d/1Kz7GkkpJxsaSePm2aTNhpcJH-0PCVjn6/view?usp=sharing) with this criteria
- [ ] attempt to bulk contact the filtered hospitals
  - [x] try to get translation of email done by alannah's contact, if not, google translate
