### ISSUE TITLE
Organise fixer

### ISSUE THREAD

**Issue by ChristinaLast** [ChristinaLast/pollution_analysis_kurdistan#34]
- [x] Call Stella 7:00pm (9:00pm uk time)
- [x] ask about rates in advance
- [x] translation of email
- [x] day job, availability from 25th-1st april
- [x] parts of kurdistan that have different dialect
- [x] feasibility of going around/near flaring sites/ to settlements near.
- [x] are people posting about air pollution/flaring online
- [x] impression on what is achievable in a few days
- [x] refugee camp
- [x] taking photos (children, flares, homes etc.)

**Comment by ChristinaLast** [comment]
### Meeting with Stella

- [Calgroup](https://shkoi-kurdistan.com/en/post/1045) owner (oil company in Kalak) 
- Payment in dollars
- Saturday already locked in.
- Not travelling to Garmian (4-5 hrs)
- Photos - agency standards, policy, people dont mind
- can say agricultural report at border.

### Tasks 
- [x] Stella to let us know about another day
- [x] Stella to check with Meethra to ask about access to the camp
- [x] @TomBrown4444 Send over details breakdown of itinerary

**Comment by ChristinaLast** [comment]
[Flaring trip itinerary](https://docs.google.com/document/d/1nVFUSFXhZRmGEn5fZ13FDXZflC6R3838_rGv3EeTMow/edit?usp=sharing)
