### ISSUE TITLE
Coordinate with front end developers/web designer content for microsite.

### ISSUE THREAD

**Issue by ChristinaLast** [ChristinaLast/pollution_analysis_kurdistan#37]
# Keng Richa <> Tom Christina

### Story audience
- Do we want to connect local story 
- Bandwidth heavy visuals are not going to help
- remember visuals need to be granularity  
- high resolution images of villages and flaring
- air pollution reading in the area (could we get this)

### Oceans.inc
- [webflow](https://webflow.com/) (custom microsite)
    -  1 page or home page
    -  scrolling interactive visuals
- home page individual story
- embeddable graphics
    - interactive maps/graphs
- ERC have funding from our side to build website
- 1/2 months to design the site.
- 

# Tasks
- [x] secure a domain
- [x] funding from our side to build website
- [x] Richa to set up slack
- [x] Send team timeline 
- [x] Map and datasets for Keng bring addressed in #54 
- [x] Christina and Tom to make webflow account and share with "co-designer" being addressed in and give team access #56
- [X] Keng to send an email about the type of account

**Comment by ChristinaLast** [comment]
@TomBrown4444's notes [here](https://docs.google.com/document/d/1wgNKJpM6G5iby0Z8hjD4aelzGxQJ4iFNNoLmXhwWp_A/edit?usp=sharing)

**Comment by ChristinaLast** [comment]
Christina's further notes [here](https://hackmd.io/Yyuey-p4TFWr6TSedVz40w)

**Comment by ChristinaLast** [comment]
Discussed with Keng and designer to start on ERC Webflow tool and add us as collaborators.
